# Generated by Django 6.0.5 on 2026-06-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('caption', models.CharField(max_length=100, verbose_name='Название')),
                ('bossname', models.CharField(max_length=150, verbose_name='Главврач')),
            ],
        ),
        migrations.CreateModel(
            name='T001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam_mo', models.CharField(max_length=100, verbose_name='Наименование подразделения')),
                ('nom_podr', models.CharField(max_length=10, verbose_name='Код подразделения в мед.орг.')),
                ('mcod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdivisions', to='attachment.lpu', verbose_name='Мед.организация')),
            ],
        ),
        migrations.CreateModel(
            name='T007',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_depth', models.CharField(max_length=100, verbose_name='Наименование участка')),
                ('nom_podr', models.CharField(max_length=10, verbose_name='Код подразделения в мед.орг.')),
                ('depth', models.CharField(max_length=10)),
                ('code_mo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='attachment.lpu', verbose_name='Мед.организация')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enp', models.CharField(max_length=16, unique=True, verbose_name='ЕНП (полис)')),
                ('fam', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('im', models.CharField(max_length=40, verbose_name='Имя')),
                ('ot', models.CharField(blank=True, max_length=40, verbose_name='Отчество')),
                ('w', models.SmallIntegerField(verbose_name='Пол (1-м, 2-ж)')),
                ('dr', models.DateField(verbose_name='Дата рождения')),
                ('lpudt', models.DateField(blank=True, null=True, verbose_name='Дата прикрепления')),
                ('lpudx', models.DateField(blank=True, null=True, verbose_name='Дата открепления')),
                ('lpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='attachment.lpu', verbose_name='Мед.организация')),
                ('lpuuch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='attachment.t007', verbose_name='Участок')),
            ],
        ),
        migrations.CreateModel(
            name='HistLpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lpudt', models.DateField(blank=True, null=True, verbose_name='Дата прикрепления')),
                ('lpudx', models.DateField(blank=True, null=True, verbose_name='Дата открепления')),
                ('lpu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='attachment.lpu')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='attachment.people')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='attachment.t001', verbose_name='Подразделение')),
                ('subdiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='attachment.t007', verbose_name='Участок')),
            ],
        ),
    ]
